### ISSUE TITLE
Improve example: glob to multiple 

### ISSUE THREAD

**Issue by dignifiedquire** [gruntjs/grunt-contrib-coffee#13]
I've found that the given example

``` js
glob_to_multiple: {
  files: grunt.file.expandMapping(['path/to/*.coffee'], 'path/to/dest/', {
    rename: function(destBase, destPath) {
      return destBase + destPath.replace(/\.coffee$/, '.js');
    }
  })
}
```

was not working correctly for me. The problem was that it resulted in output files like this:

``` bash
# Actual
path/to/path/to/dest/file.js
# Expected
path/to/dest/file.js
```

This is an improved version (working with grunt@0.4.0rc7) that should fix this problem.

``` js
var path = require('path');

glob_to_multiple: {
  files: grunt.file.expandMapping(['*.coffee'], 'path/to/dest', {
    cwd: 'path/to',
    rename: function(destBase, destPath) {
      return path.join(destBase, destPath.replace(/\.coffee$/, '.js'));
    }
  })
}
```

**Comment by nottinhill** [comment]
Here's a great example that is highly dynamic and ready-to-go: http://stackoverflow.com/questions/23893292/creating-grunt-tasks-for-compiling-coffeescript-files-recursively-inside-directo/29694932#29694932
