### ISSUE TITLE
sourceMapDir

### ISSUE THREAD

**Issue by evanworley** [gruntjs/grunt-contrib-coffee#164]
It would be nice if there was a way to specify a source maps root directory. Instead of sourceMapDir being the literal directory where source maps are placed, I'd like to put all the source maps into a particular directory, but then maintaining their original path.

**Comment by arthurvr** [comment]
Just wondering, may I ask why do you want this? Does it add any more value to the functionality? I fail to think about a use case.

**Comment by evanworley** [comment]
Hi @arthurvr - I'd like the source maps to be deployed in an identical structure as their target files. So /js/foo/bar/lib.js would have source maps at /sourceMaps/foo/bar/lib.coffee. This makes it easy to do a simple transformation to find the source maps, and will allow integrating our sourceMaps into tools like Errorception. The other issue is that I actually have many files named view.js, the only thing that differentiates the file is the path. Does this help at all?

**Comment by shama** [comment]
Fixed by https://github.com/gruntjs/grunt-contrib-coffee/pull/183
