### ISSUE TITLE
Update coffeescript to 1.9.1

### ISSUE THREAD

**Issue by husa** [gruntjs/grunt-contrib-coffee#175]
Coffeescript 1.9.0 was released.
https://github.com/jashkenas/coffeescript/releases/tag/1.9.0

**Comment by rcrichton** [comment]
+1

**Comment by rcrichton** [comment]
I just gave this a go. It looks like we will have to wait for a 1.9.1 coffeescript release with this fix else a number of tests fail: https://github.com/jashkenas/coffeescript/issues/3822

**Comment by alexiskattan** [comment]
Hi looks great.  Is there a list or summary of the changes from 1.8.0 to 1.9.0?

**Comment by husa** [comment]
@alexiskattan take a look at
https://github.com/jashkenas/coffeescript/compare/1.8.0...1.9.0
or http://coffeescript.org/#changelog

**Comment by jonywtf** [comment]
+1

**Comment by husa** [comment]
UPD: coffeescript 1.9.1 released 
http://coffeescript.org/#changelog
