### ISSUE TITLE
Documentation doesn't say what examples do/how to start

### ISSUE THREAD

**Issue by joallard** [gruntjs/grunt-contrib-coffee#179]
It's my first time with creating a package, Grunt, everything. Reading the readme, I can see an example of a file, but neither the described options nor the example file say what the `compile*` instructions do.

**Comment by joallard** [comment]
Never mind, I found that the example is explained in the comments and you have to scroll right. I just wanted to point out it's not easy to read for beginners/if you don't know it's there. You can close this if you want.

**Comment by sindresorhus** [comment]
The examples are only there for convenience. Read the grunt task to actually learn how grunt works, which is knowledge you can apply to any grunt task.
