### ISSUE TITLE
Canerunt-contrib-coffee be 

### ISSUE THREAD

**Issue by elgubenis** [gruntjs/grunt-contrib-coffee#180]

**Comment by elgubenis** [comment]
hi,
i would like to know what is prefered, using grunt to compile coffee-script to js or using the register method from the coffee-script npm to require coffee-script directly (is it compiled in runtime? every time you require a coffee-script? or is every coffee file just compiled once, maybe on starting the node?

serverside

**Comment by sindresorhus** [comment]
Never compile at runtime.

**Comment by MoLLIa** [comment]
Could you please give an explanation or documentation link to read what disadvantages in compilation at a runtime?
Thanks.

**Comment by elgubenis** [comment]
so is the answer to "is it compiled in runtime?" a yes?
"Never compile at runtime" is what i want, but i dont know if the iced-coffee-script and coffee-script /register extension plugins compile at runtime or not, maybe they dont, so someone should/could use them (serverside)

**Comment by elgubenis** [comment]
@MoLLIa you dont need a explanation or documentation for that, everything what the cpu/memory needs to do additional in the runtime (what also could have been done before running the script) is bad.

there are several things, like handlebars or other template engines for example which can be compiled before runtime and though dont consume any resources being compiled at runtime, because they come pre-compiled
