### ISSUE TITLE
Task targets

### ISSUE THREAD

**Issue by mchicote** [gruntjs/grunt-contrib-coffee#182]
Hi
I'm trying to specify different targets in one file using the following:
````
'use strict';

module.exports = function(grunt) {
  return {
      stage: {
          glob_to_multiple: {
              expand: true,
              nonull: true,
              cwd: 'src/js/',
              src: ['*.coffee', 'config/stage.coffee'],
              dest: '.tmp/js/',
              ext: '.js'
          }
      }
  };
};
````
But when I execute the task using ````grunt coffee:stage ```` no files are copied. Any ideas?

````
Running "coffee:stage" (coffee) task
>> 0 files created.

Done, without errors.

````

Thanks!

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by mchicote** [comment]
http://stackoverflow.com/questions/29513964/target-using-grunt-contrib-coffee 
Thanks @sindresorhus
