### ISSUE TITLE
Do not concat or compile if there are no changes

### ISSUE THREAD

**Issue by nathancarter** [gruntjs/grunt-contrib-coffee#186]
Enhancement request:
 * If source files that would be concatenated have not changed (i.e., timestamp is less than or equal to that of the generated output file) then do not re-generate the output file.
 * If source file that would be compiled has not changed then do not re-run CoffeeScript compiler
There could be an option for enabling/disabling this feature, for environments in which it is undesirable.

**Comment by sindresorhus** [comment]
Use https://github.com/tschaub/grunt-newer

**Comment by nathancarter** [comment]
Great tip, thank you. Sorry for the unneeded issue. 

I read 4-5 doc pages on learning grunt, and didn't see that task anywhere. It's pretty crucial functionality in most cases! Wonder why the tutorials don't mention it.
