### ISSUE TITLE
not using latest version of Coffeescript

### ISSUE THREAD

**Issue by ghostsquad** [gruntjs/grunt-contrib-coffee#190]
Coffeescript is up to version 1.10
this is using 1.9.3

**Comment by shaunc** [comment]
https://github.com/gruntjs/grunt-contrib-coffee/pull/189

This means that defaults in destructuring don't work. NB to get this to work the version of coffeescript in grunt itself also needs to be bumped.

**Comment by XhmikosR** [comment]
https://github.com/gruntjs/grunt-contrib-coffee/pull/187
