### ISSUE TITLE
Vulnerability issue > upgrade lodash

### ISSUE THREAD

**Issue by fmagaldea** [gruntjs/grunt-contrib-coffee#200]
Recommended version is >=4.17.5, see command "npm audit".

**Comment by bennyn** [comment]
@vladikoff Can you update "lodash" and create a new release? 

Otherwise projects which rely on "grunt-contrib-coffee" will see this in their repository header:

![image](https://user-images.githubusercontent.com/469989/54117933-30b7a880-43f2-11e9-9b28-2337087e4795.png)
