### ISSUE TITLE
Extra '/' in sourceMap coffee file lookup?

### ISSUE THREAD

**Issue by mleveck** [gruntjs/grunt-contrib-coffee#75]
I added the `sourceMap: true` option to my Gruntfile.js.  I use coffescript 1.6.2. What it produces looks about right.  However, from hello.coffee, I still only get hello.js in my Chrome sources.  If I set a breakpoint, I get this this error:
`Cannot GET /app/scripts//hello.coffee`

**When I run grunt server:**
**My coffeescript file is:**
app/scripts/hello.coffee
**the generated js and js.map files are:**
.tmp/scripts/hello.js
.tmp/scripts/hello.js.map

**The bottom of .tmp/scripts/hello.js reads:**
`/*
//@ sourceMappingURL=hello.js.map
*/`

**.tmp/scripts/hello.js.map  is:**
`{
  "version": 3,
  "file": "hello.js",
  "sourceRoot": "../../app/scripts/",
  "sources": [
    "hello.coffee"
  ],
  "names": [],
  "mappings": "AAAA;CAAA,CAAA,CAAA,IAAO,mBAAP;CAAA"
}`

Thanks,
Matt

**Comment by KevinSheedy** [comment]
Same problem here. My filesystem paths don't match my web url paths. My source code is like this:
```
\
    \.tmp
        \main.js
        \main.js.map
    \app
        \main.coffee
    \docs
    \test
```

So my `main.js.map` file contains:

    "sourceRoot": "../app/main.coffee"

I've configured my server to have two roots: **.tmp** and **app**. I could have set the server root as **`\`** but that would have made everything in the whole repo available. So my js and coffee are available at the following urls:

    http://localhost/main.js
    http://localhost/main.coffee

But instead, my browser requests:

    http://localhost/app/main.coffee

Can we reopen this issue?
Any way of controlling the `sourceRoot`?

**Comment by scottydawg** [comment]
I see two implementation options: 

- Add a config option to manually override the sourceRoot
- Add a config option to copy .coffee files into the output directory

Or both, since they might be useful in different scenarios (prod vs. non-prod environments, etc.). Thoughts?

**Comment by KevinSheedy** [comment]
For me, overriding the `sourceRoot` would be preferable. On my current project, we only want .coffee files in our developer environments and not on our test or production environments. We'd also prefer not to copy the .coffee files to the .tmp folder as this is an extra step that takes time and creates duplication.

An option to copy .coffee files to the output directory could potentially be useful, but this functionality is already available through [grunt-contrib-copy](https://github.com/gruntjs/grunt-contrib-copy). IMHO, I'd wait and see if anyone requests it explicitly.
