### ISSUE TITLE
If you omit { ext:".js" } from your gruntfile, it over-writes your .coffee file with javascript!

### ISSUE THREAD

**Issue by nickperkinslondon** [gruntjs/grunt-contrib-coffee#97]
( and your "dest" is the same as your "src" )

...and if you didn't have your coffeescript saved somewhere....it's gone!
I thought it would somehow default to creating ".js" files!
It should never overwrite a source file, no matter what.

**Comment by bcherny** [comment]
@shama what is an example use case where you would want to overwrite a .coffee file that is actually coffeescript with a .coffee file that is javascript?

**Comment by shama** [comment]
@bcherny Feel free to send a PR to default it to `.js`.
